language: node_js
node_js:
  - "10"

branches:
  only:
    - master

script:
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: bash build-scripts/deploy.sh $GITHUB_TOKEN
    on:
      branch: master
