language: node_js
node_js:
  - "10"

branches:
  only:
    - master
    - gh-pages

script:
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: master
